formApp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = "formApp"

urlpatterns = [
    path('',views.landing_page_view,name="formApp_page"),
    path('delete/<int:id>', views.delete, name="delete"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

story_6/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("formApp.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += staticfiles_urlpatterns()

formApp/models.py
from django.db.models import *

# Create your models here.

class Status(Model):
    text = TextField(max_length=300)
    date = DateField(auto_now_add=True)
    time = TimeField(auto_now_add=True)

formApp/forms.py
from formApp.models import Status
import django.forms as forms

class TheForm(forms.ModelForm):

    class Meta:
        model = Status
        fields = "__all__"
 

formApp/views.py
from django.shortcuts import render,redirect
from formApp.models import Status
from formApp.forms import TheForm
# Create your views here.

def landing_page_view(request):
    statuses = Status.objects.all()
    if(request.method=="POST"):
        form = TheForm(request.POST)
        if(form.is_valid()):
            status = Status(
                text = form.cleaned_data["text"],
            )
            status.save()
            return redirect("formApp:formApp_page")

    form = TheForm()
    return render(request,"formApp/landing_page.html",{"statuses":statuses, "form":form})

def delete(request, id):
    status = Status.objects.get(pk=id)
    status.delete()
    return redirect("formApp:formApp_page")

formApp/templates/formApp/landing_page.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container text-center " id="mainContainer">
        <h1>Ayo, Wassup !</h1>
        <p>You want to add status?</p>
        <p>Awesome, just click below...</p></p>

        <!-- Button trigger modal -->
        <div class="container" id="modalCtn">
            <button type="button" id="modalBtn" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">+</button>
        </div>
        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Status</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'formApp:formApp_page' %}" method="POST" class="text-center">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_text">Write your thought...</label>
                            {{ form.text }}
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary" id="modalSubmit">Save changes</button>
                        </div>
                    </form>
                </div>
            </div>
            </div>
        </div>
        <!-- <div class="container" id="myPic">
            <img src="UNADJUSTEDNONRAW_thumb_1120.jpg" class="img-fluid" alt="xxx">
        </div> -->
    </div>

    <div class="row text-center" id="cardCtn">
        {% for status in statuses %}
        <div class="col-md-4">
            <form action="{% url 'formApp:delete' status.id %}" method="POST">
            {% csrf_token %}
            <div class="card">
                <div class="card-header">{{ status.date }} at {{ status.time }}</div>
                <div class="card-body">
                    <p class="card-text">{{ status.text }}</p>
                    <button type="submit" style="float: right;" class="btn btn-warning">Delete</button>
                </div>
            </div>
            </form>
        </div>
        {% endfor %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>